# Generated by Django 2.1.5 on 2019-01-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(upload_to='import/', verbose_name='CSV File')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=21, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=21, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(max_length=7, unique=True, verbose_name='imo')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='positions',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Ships'),
        ),
    ]
